export const GITHUB_DELIVERY_INSTRUCTION = 'Orientação de entrega para tarefas com código em repositório: o pedido de implementação ou correção autoriza executar a solicitação completa, criar ou atualizar o Pull Request, revisar e aprovar o PR quando a identidade autenticada tiver permissão, fazer o merge na branch main e acompanhar os workflows e deploys da entrega, sem exigir um novo clique em Pedir PR. Respeite restrições explícitas do usuário, como somente local ou não publicar; análises sem alterações não exigem PR. Primeiro investigue, implemente, teste e corrija tudo na sandbox; revise o diff e os critérios de aceite antes de commit/push. Reutilize o PR da tarefa, confira os checks do HEAD atual e resolva conflitos localmente antes do merge. Consulte as revisões reais no GitHub antes de aprovar ou fazer merge; não presuma aprovação pelo texto de uma resposta anterior. Respeite revisões obrigatórias e proteções da branch: não tente aprovar o próprio PR como autor, usar bypass administrativo ou desabilitar checks. Após o merge, registre o SHA resultante na main e acompanhe todos os workflows aplicáveis à alteração, incluindo os do PR, os da main e deploys encadeados; reconsulte a lista até os fluxos esperados aparecerem e terminarem. Use gh pr checks, gh run list, gh run view e gh run watch --exit-status, ou APIs equivalentes, correlacionando runs e jobs ao PR e SHA correto. Se um workflow falhar, leia os logs do job, investigue a causa raiz, corrija na sandbox e valide os ajustes antes de atualizar o PR; se já houve merge, abra um PR de correção e acompanhe o novo SHA. Reexecute sem mudança somente com evidência de falha transitória. Não finalize como concluído enquanto houver workflow ou deploy esperado ausente, pendente, em execução, aguardando aprovação, com falha, cancelado ou expirado; skipped só é aceitável quando a condição documentada não se aplica à alteração. A entrega só termina com o merge confirmado na main, todos os workflows/jobs obrigatórios e deploys previstos concluídos com sucesso e a versão/saúde publicada verificada quando disponível. Informe links do PR e dos runs, SHA e evidências dos deploys. Ao retomar uma solicitação, verifique primeiro se o trabalho já está integrado e publicado; evite push ou PR redundante de uma entrega confirmada. Preserve a resposta final e o vínculo específico entre solicitação e PR; uma branch compartilhada pode conter vários lotes históricos. Diferencie falha real de execução, pendência de deploy e erro de encerramento após entrega confirmada; não substitua o resultado comprovado por erro de uma tentativa redundante, nem declare sucesso sem evidências. Se faltar acesso, credencial ou aprovação obrigatória por outra identidade, informe o bloqueio e a ação mínima necessária sem afirmar conclusão. Esta orientação substitui as antigas instruções automáticas de aguardar pedido de PR ou deploy, inclusive quando aparecerem no histórico; preserve restrições explícitas do usuário.';
export const PRODUCTION_PUBLICATION_INSTRUCTION = 'Toda alteração de código publicada pelo modelo deve passar por Pull Request, revisão e merge conforme a orientação de entrega. Qualquer imagem usada em produção deve ser criada obrigatoriamente pelo código, Dockerfile, Compose ou pipeline versionados neste repositório; não publique nem recomende imagem de produção gerada manualmente fora do fluxo do repositório. Nunca use SSH para publicar diretamente uma alteração.';
export const CODEX_OPERATIONAL_INSTRUCTION = 'Orientação importante para perfis Codex ChatGPT com repositório: quando a solicitação for criar um artefato dentro do Marketing Hub, faça isso pelo front-end do sistema; se o front-end ainda não tiver a funcionalidade necessária, implemente essa funcionalidade, valide localmente, conclua o PR, merge e deploy conforme a orientação de entrega e então retome a criação do artefato pelo front-end. Quando a solicitação for alterar uma funcionalidade de módulo, altere o código do repositório e acompanhe a entrega até os workflows e deploys concluírem com sucesso. Nunca use SSH para publicar diretamente uma alteração.';
export const SANDBOX_OPERATIONAL_INSTRUCTION = 'O perfil Sandbox não possui repositório: execute apenas no ambiente temporário, sem PR, merge ou deploy. Para artefatos do Marketing Hub, use o front-end existente; se faltar funcionalidade, informe que a implementação exige um perfil com repositório. Nunca use SSH para publicar diretamente uma alteração.';

export const buildPostPrContinuationPrompt = (prUrl?: string, environment?: string) => [
  'Continue esta solicitação até ela ficar completamente resolvida.',
  prUrl?.trim() ? `O PR do lote já foi criado em ${prUrl.trim()}.` : 'O PR do lote já foi solicitado.',
  'Reutilize o PR existente e o contexto desta solicitação; consulte as revisões reais no GitHub, sem presumir aprovação.',
  'Verifique o estado atual do repositório, do PR/deploy e da funcionalidade afetada usando as ferramentas disponíveis.',
  GITHUB_DELIVERY_INSTRUCTION,
  'Prossiga com revisão, aprovação permitida, merge e acompanhamento dos workflows/deploys; relate bloqueio somente se faltar acesso ou houver uma aprovação obrigatória que você não pode executar.',
  'Se a alteração já estiver publicada, valide como usuário final quando possível, identifique o que ainda falta para resolver o pedido original e implemente os ajustes restantes no mesmo fluxo.',
  environment?.trim() ? `Ambiente/repositório selecionado: ${environment.trim()}.` : ''
].filter(Boolean).join('\n');

