#!/usr/bin/env bash
set -Eeuo pipefail

destination="$1"
shift
[ "${destination}" = root@fixture.test ] || exit 77

if [ "$#" -eq 4 ] && [ "$1 $2 $3" = "docker image inspect" ]; then
  docker image inspect "$4" | jq '.[0].RootFS.Layers += ["sha256:0000000000000000000000000000000000000000000000000000000000000000"]'
  exit 0
fi

exec "$@"
