CREATE TABLE video_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description LONGVARCHAR,
    product_name VARCHAR(255),
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    language VARCHAR(10) NOT NULL DEFAULT 'pt-BR',
    tone VARCHAR(80),
    target_audience VARCHAR(255),
    primary_goal VARCHAR(255),
    call_to_action_url VARCHAR(500),
    avatar_style VARCHAR(100),
    hero_image_url VARCHAR(500),
    owner_email VARCHAR(255),
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE video_scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    sequence_index INT NOT NULL,
    title VARCHAR(255),
    script LONGVARCHAR NOT NULL,
    visual_style VARCHAR(100),
    voiceover_url VARCHAR(500),
    duration_seconds INT,
    call_to_action_label VARCHAR(100),
    primary_asset_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_video_scenes_project FOREIGN KEY (project_id) REFERENCES video_projects(id) ON DELETE CASCADE,
    CONSTRAINT uk_video_scenes_project_sequence UNIQUE (project_id, sequence_index)
);

CREATE TABLE video_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    label VARCHAR(150) NOT NULL,
    source VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_video_assets_project FOREIGN KEY (project_id) REFERENCES video_projects(id) ON DELETE CASCADE
);
CREATE INDEX idx_video_assets_project_type ON video_assets(project_id, type);

CREATE TABLE video_render_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    provider VARCHAR(100) NOT NULL,
    provider_job_id VARCHAR(150),
    status VARCHAR(40) NOT NULL DEFAULT 'queued',
    render_profile VARCHAR(150),
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    output_url VARCHAR(500),
    failure_reason LONGVARCHAR,
    CONSTRAINT fk_video_render_jobs_project FOREIGN KEY (project_id) REFERENCES video_projects(id) ON DELETE CASCADE
);
CREATE INDEX idx_video_render_jobs_project ON video_render_jobs(project_id);
