CREATE TABLE growth_missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product VARCHAR(150) NOT NULL,
    objective VARCHAR(500) NOT NULL,
    target_sales INT NOT NULL,
    budget_limit DECIMAL(14,2) NOT NULL,
    ends_at DATE,
    status VARCHAR(20) NOT NULL,
    visitors BIGINT NOT NULL DEFAULT 0,
    cta_clicks BIGINT NOT NULL DEFAULT 0,
    checkouts_started BIGINT NOT NULL DEFAULT 0,
    sales_approved BIGINT NOT NULL DEFAULT 0,
    briefings_completed BIGINT NOT NULL DEFAULT 0,
    deliveries_completed BIGINT NOT NULL DEFAULT 0,
    refunds BIGINT NOT NULL DEFAULT 0,
    revenue DECIMAL(14,2) NOT NULL DEFAULT 0,
    spend DECIMAL(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_growth_missions_status_updated ON growth_missions(status, updated_at);
