CREATE TABLE processes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(80) NOT NULL UNIQUE,
    text VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE codex_request_processes (
    request_id BIGINT PRIMARY KEY,
    process_number VARCHAR(80) NOT NULL,
    process_text VARCHAR(500) NOT NULL,
    CONSTRAINT fk_codex_request_processes_request FOREIGN KEY (request_id) REFERENCES codex_requests (id) ON DELETE CASCADE
);
