ALTER TABLE IF EXISTS products DROP CONSTRAINT IF EXISTS uk_products_slug;
ALTER TABLE IF EXISTS products DROP CONSTRAINT IF EXISTS uk_products_external_id;
ALTER TABLE IF EXISTS products DROP COLUMN IF EXISTS slug;
ALTER TABLE IF EXISTS products DROP COLUMN IF EXISTS external_id;
ALTER TABLE codex_requests ADD COLUMN IF NOT EXISTS product_name VARCHAR(150);
