spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:hub;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

hub:
  github:
    org-default: ${GITHUB_ORG_DEFAULT:}
    app-id: ${GITHUB_APP_ID:}
    installation-id: ${GITHUB_INSTALLATION_ID:0}
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:}
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: ${OPENAI_MODEL:gpt-4.1-mini}
  codex:
    api-url: ${CODEX_API_URL:https://api.openai.com}
    model: ${CODEX_MODEL:gpt-5-codex}
  logs:
    max-chars: 20000

server:
  port: 8080
