spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.jdbc.time_zone: UTC
  flyway:
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

hub:
  github:
    org-default: ${GITHUB_ORG_DEFAULT:}
    app-id: ${GITHUB_APP_ID:}
    installation-id: ${GITHUB_INSTALLATION_ID:0}
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:}
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: ${OPENAI_MODEL:gpt-4.1-mini}
  logs:
    max-chars: 20000

server:
  port: 8080
