name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build backend
        run: mvn -f apps/backend -B test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json
      - name: Install deps
        run: npm --prefix apps/frontend ci
      - name: Lint
        run: npm --prefix apps/frontend run lint

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ai-hub-backend:latest
            ghcr.io/${{ github.repository_owner }}/ai-hub-backend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ai-hub-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ai-hub-backend:buildcache,mode=max
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ai-hub-frontend:latest
            ghcr.io/${{ github.repository_owner }}/ai-hub-frontend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ai-hub-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ai-hub-frontend:buildcache,mode=max

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - backend
      - frontend
      - docker
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: 191.252.120.96
      DEPLOY_USER: root
      REMOTE_PATH: /root/ai-hub
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure SSH
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          install -m 700 -d ~/.ssh
          printf '%s\n' "${VPS_SSH_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf '%s\n' "SSH_COMMON_ARGS=-i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -o TCPKeepAlive=yes -o ConnectTimeout=60" >> "$GITHUB_ENV"
      - name: Prepare remote directory
        run: |
          ssh ${SSH_COMMON_ARGS} "${DEPLOY_USER}@${DEPLOY_HOST}" "mkdir -p ${REMOTE_PATH}"
      - name: Sync repository to VPS
        run: |
          rsync -az --delete \
            -e "ssh ${SSH_COMMON_ARGS}" \
            --exclude '.git/' \
            --exclude 'node_modules/' \
            ./ "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_PATH}"
      - name: Authenticate registry on VPS
        if: env.GHCR_USERNAME != '' && env.GHCR_TOKEN != ''
        run: |
          ssh ${SSH_COMMON_ARGS} "${DEPLOY_USER}@${DEPLOY_HOST}" "docker login ghcr.io -u '${GHCR_USERNAME}' --password-stdin" <<< "${GHCR_TOKEN}"
      - name: Publish frontend and backend
        run: |
          ssh ${SSH_COMMON_ARGS} "${DEPLOY_USER}@${DEPLOY_HOST}" "set -euo pipefail && cd ${REMOTE_PATH} && docker compose pull && docker compose up -d"
